main:
  data_path: ../../../data/filtereddb_st.db
  model_path: ../../../models/t5_4.bin

notebook:
  data_path: ../../../datasets/filtereddb_st.db
  model_path: ../../../models/t5_4.bin

header_content: True
num_evidence: 10 # how many Evidences you want to get
table_per_page: 3 # how many tables per page you want to scan
evidence_per_table: 4 # how many Evidences from the same table
column_per_table: 3 # how many cells for 1 Evidence
seed: 43 # used for reproducibility

